; PlatformIO Project Configuration File for Mixer Controller
; Board: Arduino Giga R1 WiFi (M7 Core)
; Microcontroller: STM32H747XI

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
lib_deps = 
    waspinator/AccelStepper @ ^1.64
    teemuatlut/TMCStepper @ ^0.7.3
